services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: taicacs-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Asia/Taipei"
      TZ: "Asia/Taipei"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/files/workflows:ro

volumes:
  n8n_data:
